# Generated by Django 5.0.7 on 2024-07-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Укажите название курса",
                max_length=150,
                null=True,
                verbose_name="Название",
            ),
        ),
    ]
