# Generated by Django 5.0.7 on 2024-07-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_lesson_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Укажите Превью",
                null=True,
                upload_to="users/avatars",
                verbose_name="Превью ",
            ),
        ),
    ]
